### ISSUE TITLE
Timeline shows misleading events when a person's role in an event is not primary

### ISSUE THREAD

**Issue by gburto01** [cdhorn/profileview#2]
I have installed this view and tested it with a copy of my family tree with the view's configuration left default.

I noticed that events are shown on a person's timeline regardless of the role of the person in the event. This leads to some misleading events appearing on a timeline. For example, my grandmother's death event is shared with my mother because my mother registered the death. My grandmother's role is "Primary" but my mother's role is a custom role called "Informant".

The side-effect of sharing an event is that my timeline and my mother's timeline both show the death event for my grandmother but attributed as the death of my mother instead - who is still very much alive!

I suggest showing events in the timeline only if the person concerned takes the primary role in the event. Using the example described above, the death event wrongly attributed to my mother wouldn't show on my timeline and on my mother's timeline the event would be correctly attributed to my grandmother.

**Comment by cdhorn** [comment]
Hello, thank you for the bug report. I knew more work was needed in that area, I was not checking for primary vs other events.  I probably need more around family events possibly at some point too. But in the mean time I just committed a change that I think should resolve the issues you saw.  If you have time to give it a spin and let me know I'd appeciate it.  In the timeline config options you can enable show role always, by default it only shows the role for non-primary events. Participants are also shown, also selectable in the config, but only if more than one was found for the event.

**Comment by gburto01** [comment]
I still see the same issue. I have created a little test tree which shows the issue. The GrampsXML for it is in the attached tar.gz.

[misleading_events.tar.gz](https://github.com/cdhorn/profileview/files/6688710/misleading_events.tar.gz)


![image](https://user-images.githubusercontent.com/55945324/122810036-c5462c00-d2c6-11eb-9a3a-ef338934c957.png)


The tree has three generations of people. Ann Black died in 2000 and the event which describes her death is shared with her daughter Mary White, who has the non-primary role of 'Informant'.

The timeline of John Green now has the death, apparently, of his mother Mary White but it's actually the death of his grandmother, Ann Black. The timeline shows the death event because his mother has a role in the death event.
![image](https://user-images.githubusercontent.com/55945324/122809928-a5af0380-d2c6-11eb-9775-d3ec4ebb26c9.png)

**Comment by cdhorn** [comment]
Thank you that was most helpful. I think that should be sorted a little better now. Please let me know if you notice other anomolies like that.

Note undated events are an issue. I made some attempt at trying to place them but it has issues.  I prototyped a different approach tonight but not happy with that either. 

Initially I was going to just discard them but would prefer not too.  I'll probably make that an option, I'm sure you noticed I like having options.  

Obviously if you only want to see the events for the person at hand disable all the relations in the options. Maybe I ought to make that the default behaviour, or provide an alternate event only view outside the timeline concept. I'll see as things progress.

**Comment by gburto01** [comment]
Looks fine now. Thanks.
